LIB_SEL4_MUSLC_SYS_MORECORE_BYTES: "0"
LIB_SEL4_MUSLC_SYS_DEBUG_HALT: false
LIB_SEL4_MUSLC_SYS_CPIO_FS: false
LIB_SEL4_MUSLC_SYS_ARCH_PUTCHAR_WEAK: false
LIB_SEL4_MUSLC_SYS_CONSTRUCTOR_PRIORITY: "201"
