LIB_ETHDRIVER_RX_DESC_COUNT: "128"
LIB_ETHDRIVER_TX_DESC_COUNT: "128"
LIB_ETHDRIVER_NUM_PREALLOCATED_BUFFERS: "512"
LIB_ETHDRIVER_PREALLOCATED_BUF_SIZE: "2048"
LIB_PICOTCP_ASYNC_DRIVER: true # LibEthdriverPicoTCBAsyncDriver=ON
