/*
 * Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
 *
 * SPDX-License-Identifier: GPL-2.0-only
 */

/*
 * This file is autogenerated by kernel/tools/hardware_gen.py
 */

#pragma once

#include <types.h>

#define MAX_NUM_REGIONS 1

struct elfloader_driver;

struct elfloader_device {
    const char *compat;
    volatile void *region_bases[MAX_NUM_REGIONS];
    struct elfloader_driver *drv;
};

struct elfloader_cpu {
    const char *compat;
    const char *enable_method;
    word_t cpu_id;
    word_t extra_data;
};

#ifdef DRIVER_COMMON
struct elfloader_device elfloader_devices[] = {
    {
        /* /amba/serial@e0001000 */
        .compat = "xlnx,xuartps",
        .region_bases = {
            (void *)0xe0001000,
        },
    },
    {
        /* /amba/slcr@f8000000/rstc@200 */
        .compat = "xlnx,zynq-reset",
        .region_bases = {
            (void *)0x200,
        },
    },
};

struct elfloader_cpu elfloader_cpus[] = {
    {
        /* /cpus/cpu@0 */
        .compat = "arm,cortex-a9",
        .enable_method = NULL,
        .cpu_id = 0x0,
        .extra_data = 0
    },
    {
        /* /cpus/cpu@1 */
        .compat = "arm,cortex-a9",
        .enable_method = NULL,
        .cpu_id = 0x1,
        .extra_data = 0
    },
    { .compat = NULL /* sentinel */ },
};
#else
extern struct elfloader_device elfloader_devices[];
extern struct elfloader_cpu elfloader_cpus[];
#endif