/* generated by /home/sunyvdong/sel4/mini_build/sel4-tutorials-manifest/tools/seL4/elfloader-tool/../cmake-tool/helpers/platform_sift.py BEGIN */
int num_memory_regions = 1;

struct memory_region {
    size_t start;
    size_t end;
} memory_region[1] = {
	{ .start = 0, .end = 1073741824 },
};
/* generated by /home/sunyvdong/sel4/mini_build/sel4-tutorials-manifest/tools/seL4/elfloader-tool/../cmake-tool/helpers/platform_sift.py END */
