CAMKES_DEFAULT_HEAP_SIZE: "1048576"
CAMKES_ERROR_HANDLER_CONFIGURABLE: false
CAMKES_ERROR_HANDLER_GUARD: false
CAMKES_ERROR_HANDLER_ABORT: false
CAMKES_ERROR_HANDLER_DISCARD: false
CAMKES_ERROR_HANDLING_MODE: "Standard"
CAMKES_ERROR_HANDLER_CONFIGURABLE: true # CAmkESErrorHandlingConfigurable=ON
CAMKES_CONNECTOR_TIMING: false
CAMKES_TLS_STANDARD: false
CAMKES_TLS_PTG: false
CAMKES_TLS_MODEL: "standard"
CAMKES_TLS_STANDARD: true # CAmkESTLSStandard=ON
