#pragma once

#define CONFIG_CAMKES_DEFAULT_HEAP_SIZE  1048576
#define CONFIG_CAMKES_ERROR_HANDLER_CONFIGURABLE  1
/* disabled: CONFIG_CAMKES_ERROR_HANDLER_GUARD */
/* disabled: CONFIG_CAMKES_ERROR_HANDLER_ABORT */
/* disabled: CONFIG_CAMKES_ERROR_HANDLER_DISCARD */
#define CONFIG_CAMKES_ERROR_HANDLING_MODE  Standard
/* disabled: CONFIG_CAMKES_CONNECTOR_TIMING */
#define CONFIG_CAMKES_TLS_STANDARD  1
/* disabled: CONFIG_CAMKES_TLS_PTG */
#define CONFIG_CAMKES_TLS_MODEL  standard
