#pragma once

#define CONFIG_CAPDL_LOADER_CC_STANDARD  1
/* disabled: CONFIG_CAPDL_LOADER_CC_REGISTERS */
#define CONFIG_CAPDL_LOADER_CALLING_CONVENTION  standard
#define CONFIG_CAPDL_LOADER_MAX_OBJECTS  20000
#define CONFIG_CAPDL_LOADER_FILLS_PER_FRAME  1
/* disabled: CONFIG_CAPDL_LOADER_WRITEABLE_PAGES */
/* disabled: CONFIG_CAPDL_LOADER_PRINT_DEVICE_INFO */
/* disabled: CONFIG_CAPDL_LOADER_PRINT_UNTYPEDS */
/* disabled: CONFIG_CAPDL_LOAD_PRINT_CAPDL_OBJECTS */
/* disabled: CONFIG_CAPDL_LOADER_STATIC_ALLOC */
