ARM_HIKEY_OUTSTANDING_PREFETCHERS: "0"
ARM_HIKEY_PREFETCHER_STRIDE: "0"
ARM_HIKEY_PREFETCHER_NPFSTRM: "0"
ARM_HIKEY_PREFETCHER_STBPFDIS: false
ARM_HIKEY_PREFETCHER_STBPFRS: false
PLAT_IMX7: false
ARCH_AARCH32: false
ARCH_AARCH64: true # KernelSel4ArchAarch64=ON
ARCH_ARM_HYP: false
ARCH_RISCV32: false
ARCH_RISCV64: false
ARCH_X86_64: false
ARCH_IA32: false
SEL4_ARCH: "aarch64"
ARCH_ARM: true # KernelArchARM=ON
ARCH: "arm"
WORD_SIZE: "64"
ARM_PLAT: "qemu-arm-virt"
PLAT_BCM2711: false
PLAT_BCM2837: false
PLAT_FVP: false
PLAT_HIKEY: false
PLAT_IMX8MQ_EVK: false
PLAT_IMX8MM_EVK: false
PLAT_MAAXBOARD: false
PLAT_ODROIDC2: false
PLAT_ODROIDC4: false
PLAT_QEMU_ARM_VIRT: true # KernelPlatformQEMUArmVirt=ON
PLAT_QUARTZ64: false
PLAT_ROCKPRO64: false
PLAT_TQMA8XQP1GB: false
PLAT_TX1: false
PLAT_TX2: false
PLAT_ZYNQMP: false
PLAT_BCM2711: false
PLAT_BCM2837: false
PLAT_FVP: false
PLAT_HIKEY: false
PLAT_IMX8MQ_EVK: false
PLAT_IMX8MM_EVK: false
PLAT_MAAXBOARD: false
PLAT_ODROIDC2: false
PLAT_ODROIDC4: false
PLAT_QEMU_ARM_VIRT: true # KernelPlatformQEMUArmVirt=ON
PLAT_QUARTZ64: false
PLAT_ROCKPRO64: false
PLAT_TQMA8XQP1GB: false
PLAT_TX1: false
PLAT_TX2: false
PLAT_ZYNQMP: false
PLAT: "qemu-arm-virt"
ARM_CORTEX_A7: false
ARM_CORTEX_A8: false
ARM_CORTEX_A9: false
ARM_CORTEX_A15: false
ARM_CORTEX_A35: false
ARM_CORTEX_A53: true # KernelArmCortexA53=ON
ARM_CORTEX_A55: false
ARM_CORTEX_A57: false
ARM_CORTEX_A72: false
ARCH_ARM_V7A: false
ARCH_ARM_V7VE: false
ARCH_ARM_V8A: true # KernelArchArmV8a=ON
AARCH64_SERROR_IGNORE: false
ARM_MACH: ""
KERNEL_MCS: false
ARM_PA_SIZE_BITS_40: true # KernelArmPASizeBits40=ON
ARM_PA_SIZE_BITS_44: false
ARM_ICACHE_VIPT: true # KernelArmICacheVIPT=ON
DEBUG_DISABLE_L2_CACHE: false
DEBUG_DISABLE_L1_ICACHE: false
DEBUG_DISABLE_L1_DCACHE: false
DEBUG_DISABLE_BRANCH_PREDICTION: false
ARM_HYPERVISOR_SUPPORT: false
ARM_GIC_V3_SUPPORT: false
AARCH64_VSPACE_S2_START_L1: false
ARM_HYP_ENABLE_VCPU_CP14_SAVE_AND_RESTORE: false
ARM_ERRATA_430973: false
ARM_ERRATA_773022: false
ARM_SMMU: false
TK1_SMMU: false
ENABLE_A9_PREFETCHER: false
EXPORT_PMU_USER: false
DISABLE_WFI_WFE_TRAPS: false
SMMU_INTERRUPT_ENABLE: false
AARCH32_FPU_ENABLE_CONTEXT_SWITCH: false
AARCH64_USER_CACHE_ENABLE: true # KernelAArch64UserCacheEnable=ON
AARCH64_SERROR_IGNORE: false
ALLOW_SMC_CALLS: false
L1_CACHE_LINE_SIZE_BITS: "6"
EXPORT_PCNT_USER: false
EXPORT_VCNT_USER: false
EXPORT_PTMR_USER: false
EXPORT_VTMR_USER: false
VTIMER_UPDATE_VOFFSET: true # KernelArmVtimerUpdateVOffset=ON
HAVE_FPU: true # KernelHaveFPU=ON
PADDR_USER_DEVICE_TOP: "1099511627776"
ROOT_CNODE_SIZE_BITS: "13"
TIMER_TICK_MS: "2"
TIME_SLICE: "5"
RETYPE_FAN_OUT_LIMIT: "256"
MAX_NUM_WORK_UNITS_PER_PREEMPTION: "100"
RESET_CHUNK_BITS: "8"
MAX_NUM_BOOTINFO_UNTYPED_CAPS: "230"
FASTPATH: true # KernelFastpath=ON
EXCEPTION_FASTPATH: false
NUM_DOMAINS: "1"
SIGNAL_FASTPATH: false
NUM_PRIORITIES: "256"
MAX_NUM_NODES: "1"
ENABLE_SMP_SUPPORT: false
KERNEL_STACK_BITS: "12"
FPU_MAX_RESTORES_SINCE_SWITCH: "64"
VERIFICATION_BUILD: false
BINARY_VERIFICATION_BUILD: false
DEBUG_BUILD: true # KernelDebugBuild=ON
HARDWARE_DEBUG_API: false
PRINTING: true # KernelPrinting=ON
KERNEL_INVOCATION_REPORT_ERROR_IPC: false
NO_BENCHMARKS: false
BENCHMARK_GENERIC: false
BENCHMARK_TRACK_KERNEL_ENTRIES: false
BENCHMARK_TRACEPOINTS: false
BENCHMARK_TRACK_UTILISATION: false
KERNEL_BENCHMARK: "none"
NO_BENCHMARKS: true # KernelBenchmarksNone=ON
ENABLE_BENCHMARKS: false
KERNEL_LOG_BUFFER: false
MAX_NUM_TRACE_POINTS: "0"
IRQ_REPORTING: true # KernelIRQReporting=ON
COLOUR_PRINTING: true # KernelColourPrinting=ON
USER_STACK_TRACE_LENGTH: "16"
KERNEL_OPT_LEVEL_O2: false
KERNEL_OPT_LEVEL_OS: false
KERNEL_OPT_LEVEL_O0: false
KERNEL_OPT_LEVEL_O1: false
KERNEL_OPT_LEVEL_O3: false
KERNEL_OPT_LEVEL: "-O2"
KERNEL_OPT_LEVEL_O2: true # KernelOptimisationO2=ON
KERNEL_OPTIMISATION_CLONE_FUNCTIONS: true # KernelOptimisationCloneFunctions=ON
KERNEL_FWHOLE_PROGRAM: false
DANGEROUS_CODE_INJECTION: false
DEBUG_DISABLE_PREFETCHERS: false
SET_TLS_BASE_SELF: false
CLZ_32: false
CLZ_64: false
CTZ_32: false
CTZ_64: false
CLZ_NO_BUILTIN: false
CTZ_NO_BUILTIN: false
