CAPDL_LOADER_CC_STANDARD: false
CAPDL_LOADER_CC_REGISTERS: false
CAPDL_LOADER_CALLING_CONVENTION: "standard"
CAPDL_LOADER_CC_STANDARD: true # CapDLLoaderCallingConventionStandard=ON
CAPDL_LOADER_MAX_OBJECTS: "20000"
CAPDL_LOADER_FILLS_PER_FRAME: "1"
CAPDL_LOADER_WRITEABLE_PAGES: false
CAPDL_LOADER_PRINT_DEVICE_INFO: false
CAPDL_LOADER_PRINT_UNTYPEDS: false
CAPDL_LOAD_PRINT_CAPDL_OBJECTS: false
CAPDL_LOADER_STATIC_ALLOC: false
